# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

IdentificationType.insert_all([
  {id: 1, short_name: "CC", long_name: "Cédula de Ciudadanía"},
  {id: 2, short_name: "TI", long_name: "Tarjeta de Identidad"}
])

Specialty.insert_all([
  {id: 1, name: "Alergia"},
  {id: 2, name: "Alergia Infantil"},
  {id: 3, name: "Inmunologia"},
  {id: 4, name: "Inmunologia Infantil"},
  {id: 5, name: "Anestesiologia"},
  {id: 6, name: "Cardioangiologia"},
  {id: 7, name: "Cardiologia"},
  {id: 8, name: "Cardiologia Geriatrica"},
  {id: 9, name: "Cardiologia Pediatrica"},
  {id: 10, name: "Hemodinamia"},
  {id: 11, name: "Cirugia Cardiovascular"},
  {id: 12, name: "Cirugia De Cabeza/Cuello"},
  {id: 13, name: "Cirugia Gastroenterolog."},
  {id: 14, name: "Cirugia General"},
  {id: 15, name: "Cirugia Infantil"},
  {id: 16, name: "Cirugia Oncologica"},
  {id: 17, name: "Cirugia Plastica"},
  {id: 18, name: "Cirugia Proctologica"},
  {id: 19, name: "Cirugia Toraxica"},
  {id: 20, name: "Cirugia Vascular"},
  {id: 21, name: "Clinica Medica"},
  {id: 22, name: "Medicina Del Deporte"},
  {id: 23, name: "Dermatologia"},
  {id: 24, name: "Dermatologia Infantil"},
  {id: 25, name: "Endocrinologia"},
  {id: 26, name: "Endocrinologia Infantil"},
  {id: 27, name: "Endocrinologia/Nuticion"},
  {id: 28, name: "Andrologia Y Est.Masc."},
  {id: 29, name: "Esterilidad Femenina"},
  {id: 30, name: "Reproduccion"},
  {id: 31, name: "Flebologia"},
  {id: 32, name: "Linfologia"},
  {id: 33, name: "Gastroenterologia"},
  {id: 34, name: "Gastroenterologia Infantil"},
  {id: 35, name: "Hepatologia"},
  {id: 36, name: "Genetica"},
  {id: 37, name: "Geriatria Y Gerontologia"},
  {id: 38, name: "Ginecologia"},
  {id: 39, name: "Ginecologia Infanto-Juvenil"},
  {id: 40, name: "Obstetricia"},
  {id: 41, name: "Tocoginecologia"},
  {id: 42, name: "Hematologia"},
  {id: 43, name: "Hematologia Infantil"},
  {id: 44, name: "Hematologia Oncologica"},
  {id: 45, name: "Hemostasia"},
  {id: 46, name: "Hemoterapia"},
  {id: 47, name: "Infectologia"},
  {id: 48, name: "Infectologia Pediatrica"},
  {id: 49, name: "Parasitologia"},
  {id: 50, name: "Forense"},
  {id: 51, name: "Medicina Del Trabajo / Laboral"},
  {id: 52, name: "Medicina Legal"},
  {id: 53, name: "Nefrologia"},
  {id: 54, name: "Nefrologia Infantil"},
  {id: 55, name: "Neumonologia"},
  {id: 56, name: "Neumonologia Infantil"},
  {id: 57, name: "Neumotisiologia"},
  {id: 58, name: "Neumotisiologia Infantil"},
  {id: 59, name: "Neurocirugia"},
  {id: 60, name: "Neurofisiologia"},
  {id: 61, name: "Neurofoniatria"},
  {id: 62, name: "Neurologia"},
  {id: 63, name: "Neurologia Infantil"},
  {id: 64, name: "Diabetes"},
  {id: 65, name: "Nutricion"},
  {id: 66, name: "Nutricion Infantil"},
  {id: 67, name: "Obesidad"},
  {id: 68, name: "Clinica Estomatologica"},
  {id: 69, name: "Oftalmologia"},
  {id: 70, name: "Oftalmologia Infantil"},
  {id: 71, name: "Oncologia"},
  {id: 72, name: "Oncologia Infantil"},
  {id: 73, name: "Otorrinolaringologia"},
  {id: 74, name: "Otorrinolaringologia Infantil"},
  {id: 75, name: "Anatomia Patologica"},
  {id: 76, name: "Citologia"},
  {id: 77, name: "Neonatologia"},
  {id: 78, name: "Pediatria"},
  {id: 79, name: "Perinatologia"},
  {id: 80, name: "Neuropsiquiatria"},
  {id: 81, name: "Psiquiatria"},
  {id: 82, name: "Psiquiatria Infanto Juvenil"},
  {id: 83, name: "Diagnostico Por Imagenes"},
  {id: 84, name: "Ecografia"},
  {id: 85, name: "Electromiografia"},
  {id: 86, name: "Medicina Nuclear"},
  {id: 87, name: "Radiologia"},
  {id: 88, name: "Radioterapia"},
  {id: 89, name: "Reumatologia"},
  {id: 90, name: "Toxicologia"},
  {id: 91, name: "Ortopedia"},
  {id: 92, name: "Ortopedia Infantil"},
  {id: 93, name: "Osteologia"},
  {id: 94, name: "Traumatologia Y Ortopedia"},
  {id: 95, name: "Traumatologia Infantil"},
  {id: 96, name: "Urologia"},
  {id: 97, name: "Urologia Infantil"},
  {id: 98, name: "Varios / Otros"},
  {id: 99, name: "Cirugia Bucomaxilofacial"},
  {id: 100, name: "Endodoncia"},
  {id: 101, name: "Clinica Estomatologica"},
  {id: 102, name: "Odontologia"},
  {id: 103, name: "Odontopediatria"},
  {id: 104, name: "Ortodoncia"},
  {id: 105, name: "Ortopedia Maxilar"},
  {id: 106, name: "Periodoncia"},
  {id: 107, name: "Anatomia Patologica Bucalmaxilofacial"},
  {id: 108, name: "Traumatologia Maxilo Facial"},
  {id: 109, name: "Diagnostico Por Imagenes Bucomaxilofacial"},
  {id: 110, name: "Protesis Dentobucomaxilar"},
  {id: 111, name: "Medicina Del Deporte"},
  {id: 112, name: "Fisiatria (Medicina Fisica Y Rehabilitacion)"},
  {id: 113, name: "Kinesiologia General"},
  {id: 114, name: "Kinesiologia En Pediatria"},
  {id: 115, name: "Kinesiologia En Cardio Respiratorio"},
  {id: 116, name: "Kinesiologia En Traumatologia Y Ortopedia"},
  {id: 117, name: "Psicologia Clinica"},
  {id: 118, name: "Psicologia Social Y/O Comunitaria"},
  {id: 119, name: "Psicologia Juridica Y/O Forense"},
  {id: 120, name: "Psicologia Laboral Y/O Del Trabajo Y/O De Las Organizaciones"},
  {id: 121, name: "Psicologia Educacional"},
  {id: 122, name: "Psicologia Sanitaria"},
  {id: 123, name: "Neuropsiquiatria"},
  {id: 124, name: "Psiquiatria"},
  {id: 125, name: "Psiquiatria Infanto Juvenil"},
  {id: 126, name: "Bioquimica"},
  {id: 127, name: "Toxicologia"},
  {id: 128, name: "Bromatologia, Nutricion Y Tecnologia De Alimentos"},
  {id: 129, name: "Biotecnologia"},
])
